window.onload = function() {
    const canvas = document.getElementById('myCanvas');
    const ctx = canvas.getContext('2d');
    ctx.fillStyle = '#90EE90';
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    const centerX = canvas.width / 2;
    const centerY = canvas.height / 2 - 10; 
    const faceRadius = 200;
    ctx.beginPath();
    ctx.arc(centerX, centerY, faceRadius, 0, Math.PI * 2);
    ctx.fillStyle = '#FFF366'; 
    ctx.fill();
    ctx.strokeStyle = '#333';
    ctx.lineWidth = 2;
    ctx.stroke();
    const eyeRadius = 15; 
    const eyeOffsetX = 70; 
    const eyeOffsetY = 50;
    ctx.beginPath();
    ctx.arc(centerX - eyeOffsetX, centerY - eyeOffsetY, eyeRadius, 0, Math.PI * 2);
    ctx.fillStyle = 'black';
    ctx.fill();
    ctx.beginPath();
    ctx.arc(centerX + eyeOffsetX, centerY - eyeOffsetY, eyeRadius, 0, Math.PI * 2);
    ctx.fillStyle = 'black';
    ctx.fill();
    ctx.beginPath();
    ctx.moveTo(centerX, centerY);
    ctx.lineTo(centerX, centerY + 35);
    ctx.strokeStyle = '#666'; 
    ctx.lineWidth = 2; 
    ctx.stroke();
    ctx.beginPath();
    ctx.arc(centerX, centerY + 55, 65, 0, Math.PI); 
    ctx.strokeStyle = '#666'; 
    ctx.lineWidth = 2; 
    ctx.stroke();
    ctx.font = 'bold 28px Arial';
    ctx.fillStyle = '#333';
    ctx.textAlign = 'center';
    ctx.fillText('The Canvas brought me to life!', centerX, centerY + faceRadius + 40);
};